name: Publish Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Publish Site
        uses: lsthomas/math-blog@gh-pages
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
